version: '3.4'

x-common-variables: &common-variables
  INFLUXDB_DB: alfalfa
  INFLUXDB_HTTP_AUTH_ENABLED: "true"
  INFLUXDB_ADMIN_USER: admin
  INFLUXDB_ADMIN_PASSWORD: password
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: password

services:
  influxdb:
    image: influxdb:1.8
    hostname: influxdb
    ports:
      - "8086:8086"
    environment: *common-variables
    restart: always
  grafana:
    image: grafana/grafana:latest
    # build:
    #   context: './grafana'
    #   args:
    #     - INFLUXDB_ADMIN_USER
    #     - INFLUXDB_ADMIN_PASSWORD
    #     - INFLUXDB_DB
    #     - INFLUXDB_HOST
    hostname: grafana
    # image: ${HISTORIAN_GUI_REGISTRY_URI}:${VERSION_TAG}
    ports:
      - "3000:3000"
    environment: *common-variables
      # - GF_SECURITY_ADMIN_USER
      # - GF_SECURITY_ADMIN_PASSWORD
      # - INFLUXDB_DB
      # - INFLUXDB_HOST
      # - INFLUXDB_ADMIN_USER
      # - INFLUXDB_ADMIN_PASSWORD
    depends_on:
      - influxdb